apiVersion: v1
kind: Namespace
metadata:
  name: proxy
  labels:
    id: c0904325
    app: wordpress-stack
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: wp
  labels:
    id: c0904325
    app: wordpress-stack
    env: dev
---
apiVersion: v1
kind: Namespace
metadata:
  name: db
  labels:
    id: c0904325
    app: wordpress-stack
    env: dev
