apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include ".releas.name" . }}
  labels:
    id: {{ .Values.labels.id }}
    app: {{ .Values.labels.app }}
    env: {{ .Values.labels.env }}
spec:
  
  replicas: {{ .Values.replicaCount }}
  
  selector:
    matchLabels:
      app: {{ .Values.labels.app }}
  template:
    metadata:
      labels:
        id: {{ .Values.labels.id }}
        app: {{ .Values.labels.app }}
        env: {{ .Values.labels.env }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "nginx-proxy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: nginx
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: nginx-config
      volumes:
        name: nginx-config
        configMap:
        - name: {{ .Release.Name }}-nginx-config

        